# .github/workflows/auto-commit.yml

name: Daily Beacon Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Run the Java application to modify the log file
      - name: Run Beacon Generator App
        run: mvn spring-boot:run

      # It is specifically designed to handle authentication correctly in workflows.
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # The commit message for the change.
          commit_message: "feat: Generate new entropy beacon for $(date -u +'%Y-%m-%d')"
          # Optional: The name of the author for the commit.
          commit_author: Entropy Beacon Bot <github-actions[bot]@users.noreply.github.com>
